name = "glerd_json"
version = "1.1.0"
description = "Gleam JSON encoders/decoders codegen using Glerd"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "glerd-json" }
gleam = ">= 1.2.1"

[dependencies]
gleam_json = ">= 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleamyshell = ">= 2.0.0"
glerd = ">= 4.2.0"
justin = ">= 1.0.1"
simplifile = ">= 1.7.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
